name: Pytest

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pytest
        run: python -m pip install -r test-requirements.txt

      - name: Run pytest
        run: pytest test-fraction.py
